#' @title S3 method metainfo
#' @description Get the information about an object.
#' @param ... Optional arguments passed to or from other methods.
#' @return The metainfo of the object.
#' @export
metainfo <- function(...) {
  UseMethod("metainfo")
}


#' @title S3 method configuration
#' @description `configuration` gets the configuration of a given object.
#' @param x An object for which the configuration should be returned.
#' @param ... Optional arguments passed to or from other methods.
#' @return The configuration of the object.
#' @export
configuration <- function(x, ...) {
  UseMethod("configuration")
}

#' @title S3 method hyperparameters
#' @description `hyperparameters` gets the possible hyperparameter values of an object.
#' @param x An object for which the hyperparameters should be returned.
#' @param ... Optional arguments passed to or from other methods.
#' @return The configuration of the object.
#' @export
hyperparameters <- function(x, ...) {
  UseMethod("hyperparameters")
}

#' @title S3 method fit
#' @description `fit` fits a model on given data.
#' @param .inducer An inducer which should be used for the model fitting.
#' @param ... Optional arguments passed to or from other methods.
#' @return A fitted model.
#' @export
fit <- function(.inducer, ...) {
  UseMethod("fit")
}

#' @title S3 method predict
#' @description `predict` predicts the value of the response variable using a fitted model.
#' @param object A fitted model which should be used for predicting on new data.
#' @param ... Optional arguments passed to or from other methods.
#' @return A fitted model.
#' @export
predict <- function(object, ...) {
  UseMethod("predict")
}

#' @title S3 method modelObject
#' @description Get the object generated by the fitted model.
#' @param model The model for which the output should be returned.
#' @param ... Optional arguments passed to or from other methods.
#' @export
modelObject <- function(model, ...) {
  UseMethod("modelObject")
}

#' @title S3 method modelInfo
#' @description Get additional information about a `Model` object.
#' @param model The model about which the information should be obtained.
#' @param ... Optional arguments passed to or from other methods.
#' @return The information about the provided `Model` object.
#' @export
modelInfo <- function(model, ...) {
  UseMethod("modelInfo")
}
