#### Models

Models <- function(data, inducer) {
  # TODO: assert*dataset*(data)
  # TODO: assert*inducer*(inducer)
  structure(list(
    data = data,
    inducer = inducer,
  ), class = "Models"
  )
}





configuration.Models <- function(model, ...) {
  # TODO: add assert Models
}


#' @title inducer: get the inducer and its configuration
#' @description
#' This function returns the inducer and the hyperparameter setting used for the model fitting.
#'
#' @param model an object of class Models, for which the inducer and the configuration should be returned.
#'
#' @return The inducer and the configuration used for the model.
#' 
#' @examples
#' TODO!!!!
#' 
#' @export
inducer.Models <- function(model, ...) {
  stopifnot("model must be of class 'Models'" = class(model) == "Models")
  cat("Inducer:", model$inducer, "\n")
  cat("Configuration:", paste(names(model$configuration), "=", unlist(model$configuration),
            collapse = ", "))
}


#' @title modelObject: get the object generated by ????
#' @description
#' This function gets the object generated by 
#'
modelObject.Models <- function(model, ...) {
  # TODO: add assert Models
}

#' @title modelInfo: get the needed training time in seconds
#' @description
#' This function 
#' @param model an object of class 'Models'.
#' @return the time needed for the training measured in seconds
#' @examples
#' 
#' @export
modelInfo.Models <- function(model, ...) {
  # TODO: add assert Models
  stopifnot("model must be of class 'Models'" = class(model) = "Models")
  return(model$training.time.sec)
  
}

predict.Models <-function(model, newdata, ...) {
  # TODO: add assert Models and assert dataframe
  # TODO: ???? dataframe or dataset as input? ?? different behaviour?
  stopifnot("model must be of class 'Models'" = class(model) = "Models")
}