#### Models
#' @title Create a Models object
#' @description
#' Create a Models object given a dataset and an inducer.
#' @param data The data given in an Dataset object.
#' @param inducer An Inducer object: The applied inducer
#' @export

Models <- function(data, inducer) {
  assert_class(data, "Dataset")
  # TODO: assert*inducer*(inducer)
  structure(list(
    data = data,
    inducer = inducer,
  ), class = "Models"
  )
}

#' @title Create a XGBoost Model
#' @description
#' Create a XGBoost Model given a dataset and an inducer
#' @export
ModelXGBoost <- function(data, inducer) {
  model <- ModelRegression(data, inducer)
  class(model) <- c("ModelXGBoost", class(model))
}

#' @title Configuration method for Models objects
#' @description Get the configuration of a Models object.
#' @param model A Models object for which the configuration should be obtained.
#' @return The configuration of the model.
#' @export
configuration.Models <- function(model, ...) {
  assert_class(model, "Models")
  return(model$configuration)
}


#' @title inducer: get the inducer and its configuration
#' @description
#' This function returns the inducer and the hyperparameter setting used for the model fitting.
#'
#' @param model an object of class Models, for which the inducer and the configuration should be returned.
#'
#' @return The inducer and the configuration used for the model.
#'
#' @examples
#' TODO!!!!
#'
#' @export
inducer.Models <- function(model, ...) {
  assert_class(model, "Models")
  cat("Inducer:", model$inducer, "\n")
  cat("Configuration:", paste(names(model$configuration), "=", unlist(model$configuration),
            collapse = ", "))
}


#' @title modelObject: get the object generated by ????
#' @description
#' This function gets the object generated by
#'
#' @export
modelObject.Models <- function(model, ...) {
  # TODO: add assert Models
}

#' @title modelInfo: get the needed training time in seconds
#' @description
#' This function
#' @param model an object of class 'Models'.
#' @return the time needed for the training measured in seconds
#' @examples
#'
#' @export
modelInfo.Models <- function(model, ...) {
  # TODO: add assert Models
  stopifnot("model has to be of class'Models'" = class(model) == "Models")
  return(model$training.time.sec)

}


#' @title Predict method for Models
#' @description
#' Predicted values based on a Models object.
#' @param model A `Models` object
#' @param newdata A `dataset` object for which the values should be fitted
#' @return the fitted values
#' @export
predict.Models <- function(model, newdata, ...) {
  # TODO: add assert Models and assert dataframe
  # TODO: ???? dataframe or dataset as input? ?? different behaviour?
  assert_class(model, "Models", msg = "model has to be of class'Models'")
  assert_class(newdata, "dataset")
  stopifnot("model has to be of class'Models'" = class(model) == "Models")
  ind <- xgboost
  return(ind)
}


# fit(.inducer = InducerXGBoost(), .data = cars, eta = 0.5, alpha = 2)

#' @title Fit XGBoost models
#' @description
#' Uses an Inducer and a dataset to fit a xgb model
#' @param .inducer A `Inducer` object
#' @param .data A `dataset` object for which the values should be fitted
#' @return an xgb object
#' @export
fit.InducerXGBoost <- function(.inducer, .data, ...) {
  ### Works with Dataset from dataset.R

  assert_class(.inducer, "Inducer")

  # TODO assert_class(.data, "Dataset")
  argumentsDots <- list(...)  # Arguments/Hyperparameter

  # TODO data aus data branch,

  # TODO ... args im Function Kopf klüger lösen, ggf alles reinschreiben

  # argumentsDots & configuration zusammenführen

  configInd <- as.list(configuration(.inducer))  # TODO if empty ? named list()
  for (arg in names(argumentsDots)) {
    configInd[[arg]] <- argumentsDots[[arg]]
  }
  pastedHyperparam <- configInd
  # pastedHyperparam <- c(configInd, argumentsDots)

  # überprüfen

  # which("nrounds" == names(configuration(.inducer))) --> aus configuration(.inducer) löschen, sonst doppelt drinnen


  if ("nrounds" %in% names(pastedHyperparam)) {  # nrounds not in params !!!
    xgb_nRound <- pastedHyperparam$nrounds
    pastedHyperparam$nrounds <- NULL  # delete otherwise twice
  } else {
    xgb_nRound <- 1  # Hyperparameter default
  }

  # old
  # data <- as.matrix(.data)
  # fittedModel <- xgboost(data = data, label = data[, "dist"], nrounds = xgb_nRound, params = pastedHyperparam)

  fittedModel <- xgboost(data = as.matrix(.data$data), label = .data$data[, .data$target], nrounds = xgb_nRound,
                         params = pastedHyperparam)




  return(fittedModel)
  # fit.InducerXGBoost(InducerXGBoost(.data = cars))
  # fit.InducerXGBoost(InducerXGBoost(), .data = cars, nrounds = 3)  # funktioniert
  ## FUNKTIONIERT
  # fit.InducerXGBoost(.inducer = InducerXGBoost(), .data = Dataset(cars, target = "dist"))
}




fit.InducerLm <- function(.inducer, .data, ...) {
  assert_class(.inducer, "Inducer")
  # assert_class(.data, "Dataset")
  # optional: check if the Inducer exists??
  data <- as.data.frame(.data)
  # TODO: how to get the formula? out of the hyperparameters??
  fittedModel <- lm(formula, data)
  return(fittedModel)
}




modelObject <- function(modelObj) {
  # TODO asserts

  print(modelObj)


}
