#### Models
#' @title Create a Models object
#' @description
#' Create a Models object given a dataset and an inducer.
#' 
#' @export

Models <- function(data, inducer) {
  assert_class(data, "Dataset")
  # TODO: assert*inducer*(inducer)
  structure(list(
    data = data,
    inducer = inducer,
  ), class = "Models"
  )
}

#' @title Create a XGBoost Model
#' @description
#' Create a XGBoost Model given a dataset and an inducer
#' @export
ModelXGBoost <- function(data, inducer) {
  model <- ModelRegression(data, inducer)
  class(model) <- c("ModelXGBoost", class(model))
}

#' @title Configuration method for Models objects
#' @description Get the configuration of a Models object.
#' @param model A Models object for which the configuration should be obtained.
#' @return The configuration of the model.
#' @export
configuration.Models <- function(model, ...) {
  assert_class(model, "Models")
  return(model$configuration)
}


#' @title inducer: get the inducer and its configuration
#' @description
#' This function returns the inducer and the hyperparameter setting used for the model fitting.
#'
#' @param model an object of class Models, for which the inducer and the configuration should be returned.
#'
#' @return The inducer and the configuration used for the model.
#' 
#' @examples
#' TODO!!!!
#' 
#' @export
inducer.Models <- function(model, ...) {
  assert_class(model, "Models")
  cat("Inducer:", model$inducer, "\n")
  cat("Configuration:", paste(names(model$configuration), "=", unlist(model$configuration),
            collapse = ", "))
}


#' @title modelObject: get the object generated by ????
#' @description
#' This function gets the object generated by 
#'
#' @export
modelObject.Models <- function(model, ...) {
  # TODO: add assert Models
}

#' @title modelInfo: get the needed training time in seconds
#' @description
#' This function 
#' @param model an object of class 'Models'.
#' @return the time needed for the training measured in seconds
#' @examples
#' 
#' @export
modelInfo.Models <- function(model, ...) {
  # TODO: add assert Models
  stopifnot("model has to be of class'Models'" = class(model) == "Models")
  return(model$training.time.sec)
  
}


#' @title Predict method for Models
#' @description
#' Predicted values based on a Models object.
#' @param model A `Models` object
#' @param newdata A `dataset` object for which the values should be fitted
#' @return the fitted values
#' @export 
predict.Models <- function(model, newdata, ...) {
  # TODO: add assert Models and assert dataframe
  # TODO: ???? dataframe or dataset as input? ?? different behaviour?
  assert_class(model, "Models", msg = "model has to be of class'Models'")
  assert_class(newdata, "dataset")
  stopifnot("model has to be of class'Models'" = class(model) == "Models")
  ind <- xgboost
  return(ind)
}