name: r-ci

on: [push, pull_request]

jobs:
  lint:
    name: Lint R Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install lintr
        run: Rscript -e 'install.packages("lintr")'

      - name: Lint R files in R
        run: Rscript -e 'lintr::lint_dir("R")'
